version: "3.9"

services:

  getaway:
    image: nginx:1.25-alpine
    container_name: ip_getaway
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro,Z
    labels:
     - "ip_getaway.version=1.0"
    networks:
      - ip_network

  users:
    build:
      context: ./services/users
    container_name: ip_users
    command: python manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - ./services/users:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    networks:
      - ip_network

  # db:
  #   image: postgres:15-alpine
  #   container_name: ip_db
  #   environment:
  #     POSTGRES_DB: users_db
  #     POSTGRES_USER: users_user
  #     POSTGRES_PASSWORD: users_pass
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   networks:
  #     - ip_network

networks:
  ip_network:
    driver: bridge

volumes:
  pgdata: