worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    limit_req_zone "test" zone=health_limit:2m rate=1r/s;
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=3r/s;
    
    # Mapas de validación
    map $http_x_api_key $missing_api_key {
        "" 1;
        "~^\s*$" 1;
        default 0;
    }

    map $http_x_origin $missing_origin {
        "" 1;
        "~^\s*$" 1;
        default 0;
    }

    server{
        listen      80;
        server_name  localhost;
        
        limit_req_status 429;

        location /check {
            add_header Content-Type text/plain;
            return 200 'Getaway OK';
        }

        location /core/api/v1 {

            if ($missing_api_key) { return 401 "x-api-key is required";}
            if ($missing_origin) { return 401 "x-origin is required";}

            add_header Content-Type text/plain;
            return 200 'Core API OK';
        }

        location /user/api/v1 {

            if ($missing_api_key) { return 401 "x-api-key is required";}
            if ($missing_origin) { return 401 "x-origin is required";}

            add_header Content-Type text/plain;
            return 200 'User API OK';
        }

        location /user/api/v2 {

            if ($missing_api_key) { return 401 "x-api-key is required";}
            if ($missing_origin) { return 401 "x-origin is required";}

            add_header Content-Type text/plain;
            return 200 'User API v2 OK';
        }

        location * {
            add_header Content-Type text/plain;
            return 404 'Not Found';
        }
    }
}