worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout 65;

    # servicios
    upstream user_services {
        server users:8000;
        keepalive 16;
    }

    limit_req_zone "test" zone=health_limit:2m rate=1r/s;
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=3r/s;
    
    # Mapas de validación
    map $http_x_api_key $missing_api_key {
        "" 1;
        "~^\s*$" 1;
        default 0;
    }

    map $http_x_origin $missing_origin {
        "" 1;
        "~^\s*$" 1;
        default 0;
    }

    server{
        listen      80;
        server_name  localhost;
        
        limit_req_status 429;

        location /check {
            add_header Content-Type text/plain;
            return 200 'Getaway OK';
        }

        location /core/api/v1 {

            if ($missing_api_key) { return 401 "x-api-key is required";}
            if ($missing_origin) { return 401 "x-origin is required";}

            add_header Content-Type text/plain;
            return 200 'Core API OK';
        }

        location = /user/api/v1 {
            return 301 /user/api/v1/;
        }

        location = /user/api/v1/docs {
            return 301 /user/api/v1/docs/;
        }

        location = /schema {
            return 301 /schema/;
        }

        location /schema/ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://user_services/schema/;
        }

        location /user/api/v1/docs/ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://user_services/gateway-docs/;
        }

        location = /user/api/v1/schema {
            return 301 /user/api/v1/schema/;
        }

        location /user/api/v1/schema/ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://user_services/schema/;
        }

        location /user/api/v1/ {

            if ($missing_api_key) { return 401 "x-api-key is required";}
            if ($missing_origin) { return 401 "x-origin is required";}

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://user_services/;
        }

        location /user/api/v2 {

            if ($missing_api_key) { return 401 "x-api-key is required";}
            if ($missing_origin) { return 401 "x-origin is required";}

            add_header Content-Type text/plain;
            return 200 'User API v2 OK';
        }

        location / {
            add_header Content-Type text/plain;
            return 404 'Not Found';
        }
    }
}