# Generated by Django 4.2.11 on 2026-04-13 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
    ]
